spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    hikari: 
      connection-timeout: 30000
      maximum-pool-size: 10
  thymeleaf: 
    mode: HTML
  profiles: 
    active: production

logging:
  level:
    org: 
      springframework: INFO

server: 
  port: ${PORT:5000}

golang:
  path: ${GOPATH}
